name: lighning ai

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest 

    steps:
      - name: Install SSH and Set Password
        run: |
          sudo apt update && sudo apt install -y openssh-server curl
          sudo service ssh start

          # Set a password for the 'runner' user
          echo "runner:Sanjay@21" | sudo chpasswd

          # Allow password authentication in SSH
          sudo sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Start SSH
        run: |
          sudo apt update && pip install tmate

          

      - name: Display SSH Connection Info
        run: tmate

      - name: Keep Runner Alive
        run: sleep infinity
        
        run: python3 24x7.py
